### ISSUE TITLE
Fehler in der Datei  "locales_quest.sql"

### ISSUE THREAD

**Issue by Dainara82** [RazzorX/GMDB_NEU#1]
Huhu
hab einen Syntaxfehler gefunden:
ERROR 1064 (42000) at line 28: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'RequestItemsText_loc3='Seid wiedereinmal gegrüßt, \$N! Seid Ihr gekommen um mi' at line 1

Zeile 28   nach zeichen 927    fehlt ein  Komma  
vor folgendem Text  wurde ein  , (komma) vefgessen

alt
`ein Ende.' 'RequestItemsText_loc3='Seid wiedereinmal`

neu
`ein Ende.',  'RequestItemsText_loc3='Seid wiedereinmal`

bitte bereinigen :) danke

**Comment by RazzorX** [comment]
Danke für den Hinweis. Ist mit dem nächsten Update behoben, also morgen schon oder am WE. :)
